use std::{env, fs, path::PathBuf};

const H3_DNS_SERVER_ENV: &str = "DHTTP_H3_DNS_SERVER";
const HTTP_DNS_SERVER_ENV: &str = "DHTTP_HTTP_DNS_SERVER";
const MDNS_SERVICE_ENV: &str = "DHTTP_MDNS_SERVICE";

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));

    let h3_dns_server = required_env(H3_DNS_SERVER_ENV);
    let http_dns_server = required_env(HTTP_DNS_SERVER_ENV);
    let mdns_service = required_env(MDNS_SERVICE_ENV);

    let bootstrap = format!(
        "// @generated by build.rs; do not edit.\n\
         pub const DHTTP_H3_DNS_SERVER: &str = {h3_dns_server:?};\n\
         pub const DHTTP_HTTP_DNS_SERVER: &str = {http_dns_server:?};\n\
         pub const DHTTP_MDNS_SERVICE: &str = {mdns_service:?};\n"
    );
    fs::write(out_dir.join("bootstrap.rs"), bootstrap)
        .expect("failed to write generated DHTTP DNS bootstrap constants");

    println!("cargo::rerun-if-env-changed={H3_DNS_SERVER_ENV}");
    println!("cargo::rerun-if-env-changed={HTTP_DNS_SERVER_ENV}");
    println!("cargo::rerun-if-env-changed={MDNS_SERVICE_ENV}");
}

fn required_env(name: &str) -> String {
    env::var(name).unwrap_or_else(|_| panic!("missing {name}; set it before building ddns"))
}
